/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.pc;

/**
 *
 * @author Juan
 */
public class DialogInstitucion extends javax.swing.JDialog {

    /**
     * Creates new form FrameNuevaInstitucion
     */
    public DialogInstitucion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblInstitucion = new javax.swing.JLabel();
        fieldInstitucion = new javax.swing.JTextField();
        lblContacto = new javax.swing.JLabel();
        fieldContacto = new javax.swing.JTextField();
        lblTeléfono = new javax.swing.JLabel();
        fieldTelefono = new javax.swing.JTextField();
        lblDireccion = new javax.swing.JLabel();
        fieldDireccion = new javax.swing.JTextField();
        panelProductos = new javax.swing.JPanel();
        lblPrecio = new javax.swing.JLabel();
        lblCombo1 = new javax.swing.JLabel();
        lblCombo2 = new javax.swing.JLabel();
        chkIndividual = new javax.swing.JCheckBox();
        lblIndividual = new javax.swing.JLabel();
        fieldPrecioIndividual = new javax.swing.JTextField();
        chkC1Individual = new javax.swing.JCheckBox();
        chkC2Individual = new javax.swing.JCheckBox();
        chkGrupal = new javax.swing.JCheckBox();
        lblGrupal = new javax.swing.JLabel();
        fieldPrecioGrupal = new javax.swing.JTextField();
        chkC1Grupal = new javax.swing.JCheckBox();
        chkC2Grupal = new javax.swing.JCheckBox();
        chkSenio = new javax.swing.JCheckBox();
        lblSenio = new javax.swing.JLabel();
        fieldPrecioSenio = new javax.swing.JTextField();
        chkC1Senio = new javax.swing.JCheckBox();
        chkC2Senio = new javax.swing.JCheckBox();
        chkCarnet = new javax.swing.JCheckBox();
        lblCarnet = new javax.swing.JLabel();
        fieldPrecioCarnet = new javax.swing.JTextField();
        chkC1Carnet = new javax.swing.JCheckBox();
        chkC2Carnet = new javax.swing.JCheckBox();
        chkLlavero = new javax.swing.JCheckBox();
        lblLlavero = new javax.swing.JLabel();
        fieldPrecioLlavero = new javax.swing.JTextField();
        chkC1Llavero = new javax.swing.JCheckBox();
        chkC2Llavero = new javax.swing.JCheckBox();
        lblPrecioCombos = new javax.swing.JLabel();
        fieldPrecioC1 = new javax.swing.JTextField();
        fieldPrecioC2 = new javax.swing.JTextField();
        btGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(420, 515));
        setMinimumSize(new java.awt.Dimension(420, 515));
        setPreferredSize(new java.awt.Dimension(420, 515));

        lblInstitucion.setText("Institucion:");

        fieldInstitucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldInstitucionActionPerformed(evt);
            }
        });

        lblContacto.setText("Contacto:");

        fieldContacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldContactoActionPerformed(evt);
            }
        });

        lblTeléfono.setText("Teléfono:");

        fieldTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldTelefonoActionPerformed(evt);
            }
        });

        lblDireccion.setText("Dirección:");

        fieldDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldDireccionActionPerformed(evt);
            }
        });

        panelProductos.setBorder(javax.swing.BorderFactory.createTitledBorder("Productos"));

        lblPrecio.setText("Precio");

        lblCombo1.setText("Combo1");

        lblCombo2.setText("Combo2");

        chkIndividual.setSelected(true);

        lblIndividual.setText("Foto Individual");
        lblIndividual.setEnabled(false);

        fieldPrecioIndividual.setEnabled(false);

        chkC1Individual.setSelected(true);

        chkGrupal.setSelected(true);

        lblGrupal.setText("Foto Grupal");

        chkC1Grupal.setSelected(true);

        lblSenio.setText("Foto Seño");

        lblCarnet.setText("Foto Carnet");

        lblLlavero.setText("Llavero");

        lblPrecioCombos.setText("Precio Combos:");

        javax.swing.GroupLayout panelProductosLayout = new javax.swing.GroupLayout(panelProductos);
        panelProductos.setLayout(panelProductosLayout);
        panelProductosLayout.setHorizontalGroup(
            panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelProductosLayout.createSequentialGroup()
                .addGroup(panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelProductosLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblPrecio)
                        .addGap(44, 44, 44))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelProductosLayout.createSequentialGroup()
                        .addGroup(panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelProductosLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblPrecioCombos))
                            .addGroup(panelProductosLayout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addGroup(panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(chkIndividual)
                                    .addComponent(chkGrupal)
                                    .addComponent(chkSenio)
                                    .addComponent(chkCarnet)
                                    .addComponent(chkLlavero))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelProductosLayout.createSequentialGroup()
                                        .addComponent(lblSenio)
                                        .addGap(40, 40, 40)
                                        .addComponent(fieldPrecioSenio, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelProductosLayout.createSequentialGroup()
                                        .addComponent(lblCarnet)
                                        .addGap(31, 31, 31)
                                        .addComponent(fieldPrecioCarnet, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelProductosLayout.createSequentialGroup()
                                        .addGroup(panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblIndividual)
                                            .addComponent(lblGrupal, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGap(18, 18, 18)
                                        .addGroup(panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(fieldPrecioGrupal)
                                            .addComponent(fieldPrecioIndividual)))
                                    .addGroup(panelProductosLayout.createSequentialGroup()
                                        .addComponent(lblLlavero)
                                        .addGap(54, 54, 54)
                                        .addComponent(fieldPrecioLlavero, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)))))
                        .addGap(27, 27, 27)))
                .addGroup(panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelProductosLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(chkC1Grupal)
                            .addComponent(chkC1Individual)
                            .addComponent(chkC1Carnet)
                            .addComponent(chkC1Llavero)
                            .addComponent(chkC1Senio))
                        .addGap(33, 33, 33)
                        .addGroup(panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkC2Grupal)
                            .addComponent(chkC2Individual)
                            .addComponent(chkC2Senio)
                            .addComponent(chkC2Carnet)
                            .addComponent(chkC2Llavero)))
                    .addGroup(panelProductosLayout.createSequentialGroup()
                        .addComponent(lblCombo1)
                        .addGap(18, 18, 18)
                        .addComponent(lblCombo2))
                    .addGroup(panelProductosLayout.createSequentialGroup()
                        .addComponent(fieldPrecioC1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(fieldPrecioC2)))
                .addGap(37, 37, 37))
        );
        panelProductosLayout.setVerticalGroup(
            panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProductosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCombo1)
                    .addComponent(lblPrecio)
                    .addComponent(lblCombo2))
                .addGap(19, 19, 19)
                .addGroup(panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelProductosLayout.createSequentialGroup()
                        .addGroup(panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(chkGrupal)
                            .addGroup(panelProductosLayout.createSequentialGroup()
                                .addGroup(panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(chkC1Individual)
                                    .addGroup(panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblIndividual)
                                        .addComponent(fieldPrecioIndividual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(chkIndividual)
                                    .addComponent(chkC2Individual))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblGrupal)
                                        .addComponent(fieldPrecioGrupal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(chkC1Grupal)
                                    .addComponent(chkC2Grupal))))
                        .addGap(5, 5, 5)
                        .addGroup(panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(chkSenio)
                                .addGroup(panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(fieldPrecioSenio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblSenio)))
                            .addGroup(panelProductosLayout.createSequentialGroup()
                                .addGroup(panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(chkC2Senio)
                                    .addComponent(chkC1Senio))
                                .addGap(1, 1, 1)))
                        .addGroup(panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkCarnet)
                            .addGroup(panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(chkC1Carnet)
                                .addGroup(panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(fieldPrecioCarnet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCarnet)))))
                    .addComponent(chkC2Carnet))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(chkLlavero)
                        .addGroup(panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(chkC1Llavero)
                            .addGroup(panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(fieldPrecioLlavero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblLlavero))))
                    .addComponent(chkC2Llavero))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldPrecioC1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldPrecioC2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPrecioCombos))
                .addGap(21, 21, 21))
        );

        btGuardar.setText("Guardar");
        btGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblInstitucion)
                    .addComponent(lblContacto)
                    .addComponent(lblTeléfono)
                    .addComponent(lblDireccion))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fieldContacto, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldInstitucion, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btGuardar)
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInstitucion)
                    .addComponent(fieldInstitucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContacto)
                    .addComponent(fieldContacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTeléfono)
                    .addComponent(fieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDireccion)
                    .addComponent(fieldDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(panelProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btGuardar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btGuardarActionPerformed

    private void fieldContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldContactoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldContactoActionPerformed

    private void fieldTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldTelefonoActionPerformed

    private void fieldInstitucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldInstitucionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldInstitucionActionPerformed

    private void fieldDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldDireccionActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btGuardar;
    private javax.swing.JCheckBox chkC1Carnet;
    private javax.swing.JCheckBox chkC1Grupal;
    private javax.swing.JCheckBox chkC1Individual;
    private javax.swing.JCheckBox chkC1Llavero;
    private javax.swing.JCheckBox chkC1Senio;
    private javax.swing.JCheckBox chkC2Carnet;
    private javax.swing.JCheckBox chkC2Grupal;
    private javax.swing.JCheckBox chkC2Individual;
    private javax.swing.JCheckBox chkC2Llavero;
    private javax.swing.JCheckBox chkC2Senio;
    private javax.swing.JCheckBox chkCarnet;
    private javax.swing.JCheckBox chkGrupal;
    private javax.swing.JCheckBox chkIndividual;
    private javax.swing.JCheckBox chkLlavero;
    private javax.swing.JCheckBox chkSenio;
    private javax.swing.JTextField fieldContacto;
    private javax.swing.JTextField fieldDireccion;
    private javax.swing.JTextField fieldInstitucion;
    private javax.swing.JTextField fieldPrecioC1;
    private javax.swing.JTextField fieldPrecioC2;
    private javax.swing.JTextField fieldPrecioCarnet;
    private javax.swing.JTextField fieldPrecioGrupal;
    private javax.swing.JTextField fieldPrecioIndividual;
    private javax.swing.JTextField fieldPrecioLlavero;
    private javax.swing.JTextField fieldPrecioSenio;
    private javax.swing.JTextField fieldTelefono;
    private javax.swing.JLabel lblCarnet;
    private javax.swing.JLabel lblCombo1;
    private javax.swing.JLabel lblCombo2;
    private javax.swing.JLabel lblContacto;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblGrupal;
    private javax.swing.JLabel lblIndividual;
    private javax.swing.JLabel lblInstitucion;
    private javax.swing.JLabel lblLlavero;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblPrecioCombos;
    private javax.swing.JLabel lblSenio;
    private javax.swing.JLabel lblTeléfono;
    private javax.swing.JPanel panelProductos;
    // End of variables declaration//GEN-END:variables
}
