package gui.pc;

import ar.com.jicaffo.clasesbd.Alumno;
import ar.com.jicaffo.clasesbd.Curso;
import ar.com.jicaffo.fotosro.BD;
import java.awt.Frame;
import java.awt.event.KeyEvent;
import java.sql.Date;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

public class DialogCurso extends javax.swing.JDialog {

    ArrayList<Alumno> arrayAlumnos = new ArrayList();
    DefaultListModel<Alumno> modeloListaAlumnos = new DefaultListModel();
    BD bd = new BD();
    int indexAlumnoSeleccionado;

    public DialogCurso() {
        initComponents();
        setVisible(true);
    }
    
    public DialogCurso(Frame owner, String title, Boolean modal) {
        super(owner, title, modal);
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoTurno = new javax.swing.ButtonGroup();
        lblInstitucion = new javax.swing.JLabel();
        cboInstitucion = new javax.swing.JComboBox<>();
        lblNombreCurso = new javax.swing.JLabel();
        fieldNombreCurso = new javax.swing.JTextField();
        lblCargarAlumnos = new javax.swing.JLabel();
        fieldNuevoAlumno = new javax.swing.JTextField();
        scrollAlumnos = new javax.swing.JScrollPane();
        listaAlumnos = new javax.swing.JList<>();
        btBorrarAlumno = new javax.swing.JButton();
        btModificarAlumno = new javax.swing.JButton();
        panelTurno = new javax.swing.JPanel();
        rbMañana = new javax.swing.JRadioButton();
        rbTarde = new javax.swing.JRadioButton();
        rbAmbos = new javax.swing.JRadioButton();
        lblComentarioABorrar = new javax.swing.JLabel();
        chkFotoSacada = new javax.swing.JCheckBox();
        fieldNroFoto = new javax.swing.JTextField();
        fieldFechaFoto = new javax.swing.JTextField();
        btGuardar = new javax.swing.JButton();
        btGuardarYOtro = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblInstitucion.setText("Institución:");

        cboInstitucion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "*Maternal" }));

        lblNombreCurso.setText("Nombre del nuevo curso:");

        lblCargarAlumnos.setText("Cargar Alumnos");

        fieldNuevoAlumno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fieldNuevoAlumnoKeyReleased(evt);
            }
        });

        listaAlumnos.setModel(modeloListaAlumnos);
        listaAlumnos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        scrollAlumnos.setViewportView(listaAlumnos);

        btBorrarAlumno.setText("Borrar");
        btBorrarAlumno.setToolTipText("");
        btBorrarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBorrarAlumnoActionPerformed(evt);
            }
        });

        btModificarAlumno.setText("Modificar");
        btModificarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btModificarAlumnoActionPerformed(evt);
            }
        });

        panelTurno.setBorder(javax.swing.BorderFactory.createTitledBorder("Turno"));

        grupoTurno.add(rbMañana);
        rbMañana.setSelected(true);
        rbMañana.setText("Mañana");

        grupoTurno.add(rbTarde);
        rbTarde.setText("Tarde");

        grupoTurno.add(rbAmbos);
        rbAmbos.setText("Ambos");

        javax.swing.GroupLayout panelTurnoLayout = new javax.swing.GroupLayout(panelTurno);
        panelTurno.setLayout(panelTurnoLayout);
        panelTurnoLayout.setHorizontalGroup(
            panelTurnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTurnoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbMañana)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbTarde)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbAmbos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTurnoLayout.setVerticalGroup(
            panelTurnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTurnoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelTurnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbMañana)
                    .addComponent(rbTarde)
                    .addComponent(rbAmbos))
                .addGap(49, 49, 49))
        );

        lblComentarioABorrar.setText("(esto ya establecería q fotos se muesran en FPpal)");

        chkFotoSacada.setText("Ya se sacó la foto ");
        chkFotoSacada.setEnabled(false);

        fieldNroFoto.setForeground(new java.awt.Color(204, 204, 204));
        fieldNroFoto.setText("Nº Foto");
        fieldNroFoto.setEnabled(false);

        fieldFechaFoto.setForeground(new java.awt.Color(204, 204, 204));
        fieldFechaFoto.setText("Fecha");
        fieldFechaFoto.setEnabled(false);

        btGuardar.setText("Guardar");
        btGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGuardarActionPerformed(evt);
            }
        });

        btGuardarYOtro.setText("Guardar y agregar otro");
        btGuardarYOtro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGuardarYOtroActionPerformed(evt);
            }
        });

        jLabel1.setText("( aaaa-[m]m-[d]d )");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btBorrarAlumno)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btModificarAlumno))
                            .addComponent(fieldNuevoAlumno, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scrollAlumnos, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(panelTurno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(chkFotoSacada)
                                                    .addComponent(lblComentarioABorrar)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(fieldNroFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(fieldFechaFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                        .addContainerGap())
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btGuardarYOtro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(12, 12, 12))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblInstitucion)
                            .addComponent(lblNombreCurso)
                            .addComponent(lblCargarAlumnos))
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cboInstitucion, 0, 162, Short.MAX_VALUE)
                            .addComponent(fieldNombreCurso))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboInstitucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblInstitucion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fieldNombreCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombreCurso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(lblCargarAlumnos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fieldNuevoAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scrollAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelTurno, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(lblComentarioABorrar)
                        .addGap(18, 18, 18)
                        .addComponent(chkFotoSacada)
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldNroFoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldFechaFoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btGuardar)
                    .addComponent(btBorrarAlumno)
                    .addComponent(btModificarAlumno)
                    .addComponent(btGuardarYOtro))
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGuardarActionPerformed

        //Guardar curso
        String nombreCurso = fieldNombreCurso.getText();
        String turno = "Mañana";
        if (rbTarde.isSelected()) {
            turno = rbTarde.getText();
        } else if (rbAmbos.isSelected()) {
            turno = rbAmbos.getText();
        }

        Curso c;
        if (chkFotoSacada.isSelected()) {
            String archivoFotoGrupal = fieldNroFoto.getText();
            Date fechaFotoGrupal = Date.valueOf(fieldFechaFoto.getText()); //Tiene que estar en formato aaaa-[m]m-[d]d

            c = new Curso(nombreCurso, turno, archivoFotoGrupal, fechaFotoGrupal);

        } else {

            c = new Curso(nombreCurso, turno);
        }

        bd.setUrlBD("jdbc:sqlite:BD/2018/Prueba1.db");
        bd.insertarCursoSinFoto(c);

        //Guardar Alumnos (recuperar primero el ID del curso recién insertado)
        if (!arrayAlumnos.isEmpty()) {
            int idCurso = bd.obtenerCursoBD(c).getIdCurso();
            for (Alumno a : arrayAlumnos) {
                a.setIdCursoAlumno(idCurso);
            }
            bd.insertarAlumnos(arrayAlumnos);
        }

        this.dispose();


    }//GEN-LAST:event_btGuardarActionPerformed

    private void btGuardarYOtroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGuardarYOtroActionPerformed
        btGuardarActionPerformed(evt);
        DialogCurso fc = new DialogCurso();
    }//GEN-LAST:event_btGuardarYOtroActionPerformed

    private void fieldNuevoAlumnoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldNuevoAlumnoKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            Alumno a = new Alumno(fieldNuevoAlumno.getText());
            arrayAlumnos.add(a);
            modeloListaAlumnos.addElement(a);
            fieldNuevoAlumno.setText("");
        }
    }//GEN-LAST:event_fieldNuevoAlumnoKeyReleased

    private void btModificarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btModificarAlumnoActionPerformed
        indexAlumnoSeleccionado = listaAlumnos.getSelectedIndex();
        if (indexAlumnoSeleccionado == -1) {
            JOptionPane.showMessageDialog(this, "Debes seleccionar un alumno de la lista para poder modificarlo.");
        } else {

            String nuevoNombre = JOptionPane.showInputDialog("Ingresa el nuevo nombre para el alumno",
                    arrayAlumnos.get(indexAlumnoSeleccionado).getNombreAlumno());
            
            arrayAlumnos.get(indexAlumnoSeleccionado).setNombreAlumno(nuevoNombre);
            modeloListaAlumnos.get(indexAlumnoSeleccionado).setNombreAlumno(nuevoNombre);
        }
    }//GEN-LAST:event_btModificarAlumnoActionPerformed

    private void btBorrarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBorrarAlumnoActionPerformed
        indexAlumnoSeleccionado = listaAlumnos.getSelectedIndex();
        if (indexAlumnoSeleccionado == -1) {
            JOptionPane.showMessageDialog(this, "Debes seleccionar un alumno de la lista para borrarlo.");
        } else {
            modeloListaAlumnos.remove(indexAlumnoSeleccionado);
            arrayAlumnos.remove(indexAlumnoSeleccionado);
        }
    }//GEN-LAST:event_btBorrarAlumnoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBorrarAlumno;
    private javax.swing.JButton btGuardar;
    private javax.swing.JButton btGuardarYOtro;
    private javax.swing.JButton btModificarAlumno;
    private javax.swing.JComboBox<String> cboInstitucion;
    private javax.swing.JCheckBox chkFotoSacada;
    private javax.swing.JTextField fieldFechaFoto;
    private javax.swing.JTextField fieldNombreCurso;
    private javax.swing.JTextField fieldNroFoto;
    private javax.swing.JTextField fieldNuevoAlumno;
    private javax.swing.ButtonGroup grupoTurno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCargarAlumnos;
    private javax.swing.JLabel lblComentarioABorrar;
    private javax.swing.JLabel lblInstitucion;
    private javax.swing.JLabel lblNombreCurso;
    private javax.swing.JList<Alumno> listaAlumnos;
    private javax.swing.JPanel panelTurno;
    private javax.swing.JRadioButton rbAmbos;
    private javax.swing.JRadioButton rbMañana;
    private javax.swing.JRadioButton rbTarde;
    private javax.swing.JScrollPane scrollAlumnos;
    // End of variables declaration//GEN-END:variables
}
