package gui.pc;

import ar.com.jicaffo.clasesbd.Alumno;
import ar.com.jicaffo.clasesbd.Curso;
import ar.com.jicaffo.fotosro.BD;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Juan
 */
public class FramePrincipal extends javax.swing.JFrame {

    // private DefaultComboBoxModel<Institucion> modeloInstituciones; // TO DO
    private DefaultComboBoxModel<Curso> modeloCursos = new DefaultComboBoxModel();
    private DefaultTableModel modeloTabla = new DefaultTableModel();
    private BD bd = new BD();
    private static String rutaBD = "P:/Proyectos Personales pCloud/FotosRo/BD";
    private static int añoActual = 2018;
    private static String ultimaBD = "Prueba1";

    public FramePrincipal() {
        cargarModelos();
        initComponents();
        this.setVisible(true);
    }

    public static String getRutaBD() {
        return rutaBD;
    }

    public static String getUltimaBD() {
        return ultimaBD;
    }

    public static int getAñoActual() {
        return añoActual;
    }

    private void cargarModelos() {
        cargarModeloCursos();
        cargarModeloInstituciones();
        cargarModeloTabla();
    }

    private void cargarModeloCursos() {
        ArrayList<Curso> cursos = bd.obtenerCursos();
        if (cursos.isEmpty()) {
            modeloCursos.addElement(new Curso("Todos los cursos*", null));
        } else {
            modeloCursos.addElement(new Curso("Todos los cursos*", null));
            for (Curso c : cursos) {
                modeloCursos.addElement(c);
            }
        }
    }
    
    private void cargarModeloInstituciones() {
        //TO DO
    }

    private void cargarModeloTabla() {
        modeloTabla.addColumn("Nombre");
        modeloTabla.addColumn("Ind.");
        modeloTabla.setColumnCount(2);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTabs = new javax.swing.JPanel();
        tabbedPane = new javax.swing.JTabbedPane();
        tabAlumnos = new javax.swing.JPanel();
        lblAño = new javax.swing.JLabel();
        cboAño = new javax.swing.JComboBox<>();
        lblInstitucion = new javax.swing.JLabel();
        cboInstitucion = new javax.swing.JComboBox<>();
        btAgregarInstitucion = new javax.swing.JButton();
        lblCurso = new javax.swing.JLabel();
        cboCurso = new javax.swing.JComboBox<>();
        btAgregarCurso = new javax.swing.JButton();
        panelAlumnos = new javax.swing.JScrollPane();
        tablaAlumnos = new javax.swing.JTable();
        btAgregarAlumno = new javax.swing.JButton();
        btModificarAlumno = new javax.swing.JButton();
        lblRegistrosEncontrados = new javax.swing.JLabel();
        panelDatosAlumno = new javax.swing.JPanel();
        lblIdAlumno = new javax.swing.JLabel();
        fieldIdAlumno = new javax.swing.JTextField();
        lblTurno = new javax.swing.JLabel();
        fieldTurno = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        fieldNombre = new javax.swing.JTextField();
        lblMaestra = new javax.swing.JLabel();
        fieldMaestra = new javax.swing.JTextField();
        panelFotoAlumno = new javax.swing.JPanel();
        lblFotoAlumno = new javax.swing.JLabel();
        panelFotos = new javax.swing.JPanel();
        lblPedidos = new javax.swing.JLabel();
        lblFechaSacada = new javax.swing.JLabel();
        lblFotoNro = new javax.swing.JLabel();
        lblIndividual = new javax.swing.JLabel();
        btMenosIndividual = new javax.swing.JButton();
        fieldPedidoIndividual = new javax.swing.JTextField();
        btMasIndividual = new javax.swing.JButton();
        fieldFechaSacadaIndividual = new javax.swing.JTextField();
        fieldNroFotoIndividual = new javax.swing.JTextField();
        lblGrupalM = new javax.swing.JLabel();
        btMenosGrupalM = new javax.swing.JButton();
        fieldPedidoGrupalM = new javax.swing.JTextField();
        btMasGrupalM = new javax.swing.JButton();
        fieldFechaSacadaGrupalM = new javax.swing.JTextField();
        fieldNroFotoGrupalM = new javax.swing.JTextField();
        lblGrupalT = new javax.swing.JLabel();
        btMenosGrupalT = new javax.swing.JButton();
        fieldPedidoGrupalT = new javax.swing.JTextField();
        btMasGrupalT = new javax.swing.JButton();
        fieldFechaSacadaGrupalT = new javax.swing.JTextField();
        fieldNroFotoGrupalT = new javax.swing.JTextField();
        lblSenioM = new javax.swing.JLabel();
        btMenosSenioM = new javax.swing.JButton();
        fieldPedidoSenioM = new javax.swing.JTextField();
        btMasSenioM = new javax.swing.JButton();
        fieldFechaSacadaSenioM = new javax.swing.JTextField();
        fieldNroFotoSenioM = new javax.swing.JTextField();
        lblSenioT = new javax.swing.JLabel();
        btMenosSenioT = new javax.swing.JButton();
        fieldPedidoSenioT = new javax.swing.JTextField();
        btMasSenioT = new javax.swing.JButton();
        fieldFechaSacadaSenioT = new javax.swing.JTextField();
        fieldNroFotoSenioT = new javax.swing.JTextField();
        lblCarnet = new javax.swing.JLabel();
        btMenosCarnet = new javax.swing.JButton();
        fieldPedidoCarnet = new javax.swing.JTextField();
        btMasCarnet = new javax.swing.JButton();
        fieldFechaSacadaCarnet = new javax.swing.JTextField();
        fieldNroFotoCarnet = new javax.swing.JTextField();
        btMasCombo1 = new javax.swing.JButton();
        btMasCombo2 = new javax.swing.JButton();
        panelPago = new javax.swing.JPanel();
        lblTotal = new javax.swing.JLabel();
        fieldTotal = new javax.swing.JTextField();
        lblPago = new javax.swing.JLabel();
        fieldPago = new javax.swing.JTextField();
        lblRestante = new javax.swing.JLabel();
        fieldRestante = new javax.swing.JTextField();
        panelObservaciones = new javax.swing.JPanel();
        scrollObs = new javax.swing.JScrollPane();
        textObs = new javax.swing.JTextArea();
        tabConfig = new javax.swing.JPanel();
        lblRutaBD = new javax.swing.JLabel();
        fieldRutaBD = new javax.swing.JTextField();
        btModificarRutaBD = new javax.swing.JButton();
        lblUltimaInstitucion = new javax.swing.JLabel();
        lblDetalleUltimaInstitucion = new javax.swing.JLabel();
        lblRutaFotos = new javax.swing.JLabel();
        fieldRutaFotos = new javax.swing.JTextField();
        btModificarRutaFotos = new javax.swing.JButton();
        lblNombreArchivos = new javax.swing.JLabel();
        fieldPreNroFoto = new javax.swing.JTextField();
        lblNroFoto = new javax.swing.JLabel();
        fieldPostNroFoto = new javax.swing.JTextField();
        btModificarNombreArchivos = new javax.swing.JButton();
        lblRutaCopiaImprenta = new javax.swing.JLabel();
        fieldRutaCopiaImprenta = new javax.swing.JTextField();
        btModificarRutaCopiaImprenta = new javax.swing.JButton();
        panelAccionesRapidas = new javax.swing.JPanel();
        btCrearCopiasImprenta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FotosRo - (Version BETA)");
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });

        lblAño.setText("Año:");

        cboAño.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2018" }));

        lblInstitucion.setText("Institución:");

        cboInstitucion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Maternal" }));

        btAgregarInstitucion.setText("+");

        lblCurso.setText("Curso:");

        cboCurso.setModel(modeloCursos);
        cboCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboCursoActionPerformed(evt);
            }
        });

        btAgregarCurso.setText("+");
        btAgregarCurso.setAlignmentX(0.5F);
        btAgregarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAgregarCursoActionPerformed(evt);
            }
        });

        tablaAlumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        panelAlumnos.setViewportView(tablaAlumnos);

        btAgregarAlumno.setText("Agregar");

        btModificarAlumno.setText("Modificar");

        lblRegistrosEncontrados.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblRegistrosEncontrados.setText(" XXX registros encontrados");

        panelDatosAlumno.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos"));

        lblIdAlumno.setText("id Alumno:");

        lblTurno.setText("Turno?:");

        lblNombre.setText("Nombre Alumno:");

        lblMaestra.setText("Nombre Maestra");

        javax.swing.GroupLayout panelDatosAlumnoLayout = new javax.swing.GroupLayout(panelDatosAlumno);
        panelDatosAlumno.setLayout(panelDatosAlumnoLayout);
        panelDatosAlumnoLayout.setHorizontalGroup(
            panelDatosAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosAlumnoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDatosAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombre)
                    .addGroup(panelDatosAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lblMaestra, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(fieldNombre, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(fieldMaestra, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(panelDatosAlumnoLayout.createSequentialGroup()
                            .addGroup(panelDatosAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblIdAlumno)
                                .addComponent(fieldIdAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(panelDatosAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(fieldTurno, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblTurno, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelDatosAlumnoLayout.setVerticalGroup(
            panelDatosAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosAlumnoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDatosAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelDatosAlumnoLayout.createSequentialGroup()
                        .addComponent(lblIdAlumno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldIdAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelDatosAlumnoLayout.createSequentialGroup()
                        .addComponent(lblTurno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldTurno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addComponent(lblNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblMaestra)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldMaestra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelFotoAlumno.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblFotoAlumno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFotoAlumno.setText("[Foto]");

        javax.swing.GroupLayout panelFotoAlumnoLayout = new javax.swing.GroupLayout(panelFotoAlumno);
        panelFotoAlumno.setLayout(panelFotoAlumnoLayout);
        panelFotoAlumnoLayout.setHorizontalGroup(
            panelFotoAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblFotoAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
        );
        panelFotoAlumnoLayout.setVerticalGroup(
            panelFotoAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblFotoAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
        );

        panelFotos.setBorder(javax.swing.BorderFactory.createTitledBorder("Fotos"));

        lblPedidos.setText("Pedidos");

        lblFechaSacada.setText("Fecha Sacada");

        lblFotoNro.setText("Foto Nº");

        lblIndividual.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblIndividual.setText("Individual:");

        btMenosIndividual.setText("-");

        fieldPedidoIndividual.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fieldPedidoIndividual.setText("0");

        btMasIndividual.setText("+");

        fieldFechaSacadaIndividual.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        fieldFechaSacadaIndividual.setText("05/11/2018");

        fieldNroFotoIndividual.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fieldNroFotoIndividual.setText("5588");

        lblGrupalM.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblGrupalM.setText("Grupal (Mña):");

        btMenosGrupalM.setText("-");

        fieldPedidoGrupalM.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fieldPedidoGrupalM.setText("0");

        btMasGrupalM.setText("+");

        fieldFechaSacadaGrupalM.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        fieldFechaSacadaGrupalM.setText("05/11/2018");

        fieldNroFotoGrupalM.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fieldNroFotoGrupalM.setText("5588");

        lblGrupalT.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblGrupalT.setText("Grupal (Tde):");

        btMenosGrupalT.setText("-");

        fieldPedidoGrupalT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fieldPedidoGrupalT.setText("0");

        btMasGrupalT.setText("+");

        fieldFechaSacadaGrupalT.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        fieldFechaSacadaGrupalT.setText("05/11/2018");

        fieldNroFotoGrupalT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fieldNroFotoGrupalT.setText("5588");

        lblSenioM.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSenioM.setText("Seño (Mña):");

        btMenosSenioM.setText("-");

        fieldPedidoSenioM.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fieldPedidoSenioM.setText("0");

        btMasSenioM.setText("+");

        fieldFechaSacadaSenioM.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        fieldFechaSacadaSenioM.setText("05/11/2018");

        fieldNroFotoSenioM.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fieldNroFotoSenioM.setText("5588");

        lblSenioT.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSenioT.setText("Seño (Tde):");

        btMenosSenioT.setText("-");

        fieldPedidoSenioT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fieldPedidoSenioT.setText("0");

        btMasSenioT.setText("+");

        fieldFechaSacadaSenioT.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        fieldFechaSacadaSenioT.setText("05/11/2018");

        fieldNroFotoSenioT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fieldNroFotoSenioT.setText("5588");

        lblCarnet.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCarnet.setText("Carnet:");

        btMenosCarnet.setText("-");

        fieldPedidoCarnet.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fieldPedidoCarnet.setText("0");

        btMasCarnet.setText("+");

        fieldFechaSacadaCarnet.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        fieldFechaSacadaCarnet.setText("Idem Indiv.");
        fieldFechaSacadaCarnet.setEnabled(false);

        fieldNroFotoCarnet.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fieldNroFotoCarnet.setText("-");
        fieldNroFotoCarnet.setEnabled(false);

        btMasCombo1.setText("C1+");

        btMasCombo2.setText("C2+");

        javax.swing.GroupLayout panelFotosLayout = new javax.swing.GroupLayout(panelFotos);
        panelFotos.setLayout(panelFotosLayout);
        panelFotosLayout.setHorizontalGroup(
            panelFotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFotosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblGrupalM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblIndividual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblGrupalT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSenioM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSenioT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCarnet, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelFotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelFotosLayout.createSequentialGroup()
                        .addComponent(btMenosCarnet, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldPedidoCarnet, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(btMasCarnet)
                        .addGap(29, 29, 29)
                        .addComponent(fieldFechaSacadaCarnet))
                    .addGroup(panelFotosLayout.createSequentialGroup()
                        .addComponent(btMenosSenioT, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldPedidoSenioT, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(btMasSenioT)
                        .addGap(29, 29, 29)
                        .addComponent(fieldFechaSacadaSenioT))
                    .addGroup(panelFotosLayout.createSequentialGroup()
                        .addComponent(btMenosSenioM, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldPedidoSenioM, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(btMasSenioM)
                        .addGap(29, 29, 29)
                        .addComponent(fieldFechaSacadaSenioM))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFotosLayout.createSequentialGroup()
                        .addComponent(btMenosGrupalT, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldPedidoGrupalT, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(btMasGrupalT)
                        .addGap(29, 29, 29)
                        .addComponent(fieldFechaSacadaGrupalT))
                    .addGroup(panelFotosLayout.createSequentialGroup()
                        .addComponent(btMenosGrupalM, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldPedidoGrupalM, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(btMasGrupalM)
                        .addGap(29, 29, 29)
                        .addComponent(fieldFechaSacadaGrupalM))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFotosLayout.createSequentialGroup()
                        .addGroup(panelFotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelFotosLayout.createSequentialGroup()
                                .addComponent(btMenosIndividual, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fieldPedidoIndividual, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6))
                            .addGroup(panelFotosLayout.createSequentialGroup()
                                .addComponent(lblPedidos)
                                .addGap(1, 1, 1)))
                        .addComponent(btMasIndividual)
                        .addGap(29, 29, 29)
                        .addGroup(panelFotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelFotosLayout.createSequentialGroup()
                                .addComponent(lblFechaSacada)
                                .addGap(3, 3, 3))
                            .addComponent(fieldFechaSacadaIndividual))))
                .addGap(28, 28, 28)
                .addGroup(panelFotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(fieldNroFotoIndividual, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(fieldNroFotoGrupalM, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(fieldNroFotoGrupalT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(fieldNroFotoSenioM, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(fieldNroFotoSenioT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblFotoNro))
                    .addComponent(fieldNroFotoCarnet, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelFotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btMasCombo1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btMasCombo2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        panelFotosLayout.setVerticalGroup(
            panelFotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFotosLayout.createSequentialGroup()
                .addGroup(panelFotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPedidos)
                    .addComponent(lblFechaSacada)
                    .addComponent(lblFotoNro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelFotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIndividual)
                    .addComponent(btMenosIndividual)
                    .addComponent(btMasIndividual)
                    .addComponent(fieldPedidoIndividual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldFechaSacadaIndividual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldNroFotoIndividual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panelFotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFotosLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelFotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblGrupalM)
                            .addComponent(btMenosGrupalM)
                            .addComponent(btMasGrupalM)
                            .addComponent(fieldPedidoGrupalM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldFechaSacadaGrupalM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldNroFotoGrupalM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelFotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblGrupalT)
                            .addComponent(btMenosGrupalT)
                            .addComponent(btMasGrupalT)
                            .addComponent(fieldPedidoGrupalT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldFechaSacadaGrupalT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldNroFotoGrupalT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelFotosLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(btMasCombo1)))
                .addGroup(panelFotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFotosLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelFotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSenioM)
                            .addComponent(btMenosSenioM)
                            .addComponent(btMasSenioM)
                            .addComponent(fieldPedidoSenioM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldFechaSacadaSenioM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldNroFotoSenioM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelFotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSenioT)
                            .addComponent(btMenosSenioT)
                            .addComponent(btMasSenioT)
                            .addComponent(fieldPedidoSenioT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldFechaSacadaSenioT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldNroFotoSenioT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(panelFotosLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(btMasCombo2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(panelFotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCarnet)
                    .addComponent(btMenosCarnet)
                    .addComponent(btMasCarnet)
                    .addComponent(fieldPedidoCarnet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldFechaSacadaCarnet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldNroFotoCarnet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelPago.setBorder(javax.swing.BorderFactory.createTitledBorder("Pago"));

        lblTotal.setText("Total:");

        fieldTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        lblPago.setText("Pagó:");

        fieldPago.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        lblRestante.setText("Restante:");

        fieldRestante.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        javax.swing.GroupLayout panelPagoLayout = new javax.swing.GroupLayout(panelPago);
        panelPago.setLayout(panelPagoLayout);
        panelPagoLayout.setHorizontalGroup(
            panelPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPagoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTotal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(lblPago)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldPago, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(lblRestante)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldRestante, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelPagoLayout.setVerticalGroup(
            panelPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPagoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(fieldRestante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblRestante))
                    .addGroup(panelPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblTotal)
                        .addComponent(fieldTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(fieldPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblPago)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelObservaciones.setBorder(javax.swing.BorderFactory.createTitledBorder("Observaciones"));

        textObs.setColumns(20);
        textObs.setRows(5);
        scrollObs.setViewportView(textObs);

        javax.swing.GroupLayout panelObservacionesLayout = new javax.swing.GroupLayout(panelObservaciones);
        panelObservaciones.setLayout(panelObservacionesLayout);
        panelObservacionesLayout.setHorizontalGroup(
            panelObservacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelObservacionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollObs)
                .addContainerGap())
        );
        panelObservacionesLayout.setVerticalGroup(
            panelObservacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelObservacionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollObs, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout tabAlumnosLayout = new javax.swing.GroupLayout(tabAlumnos);
        tabAlumnos.setLayout(tabAlumnosLayout);
        tabAlumnosLayout.setHorizontalGroup(
            tabAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabAlumnosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabAlumnosLayout.createSequentialGroup()
                        .addGroup(tabAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(tabAlumnosLayout.createSequentialGroup()
                                .addComponent(btAgregarAlumno)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btModificarAlumno)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblRegistrosEncontrados, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(panelAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(tabAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelFotos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(tabAlumnosLayout.createSequentialGroup()
                                .addComponent(panelDatosAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(panelFotoAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(panelPago, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelObservaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(tabAlumnosLayout.createSequentialGroup()
                        .addComponent(lblAño)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cboAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblInstitucion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cboInstitucion, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btAgregarInstitucion)
                        .addGap(66, 66, 66)
                        .addComponent(lblCurso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cboCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btAgregarCurso)))
                .addContainerGap())
        );
        tabAlumnosLayout.setVerticalGroup(
            tabAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabAlumnosLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(tabAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboInstitucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblInstitucion)
                    .addComponent(lblCurso)
                    .addComponent(lblAño)
                    .addComponent(cboAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAgregarCurso)
                    .addComponent(btAgregarInstitucion))
                .addGap(18, 18, 18)
                .addGroup(tabAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(tabAlumnosLayout.createSequentialGroup()
                        .addGroup(tabAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panelDatosAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelFotoAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelFotos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelObservaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(panelAlumnos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAgregarAlumno)
                    .addComponent(lblRegistrosEncontrados)
                    .addComponent(btModificarAlumno))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabbedPane.addTab("Alumnos", tabAlumnos);

        lblRutaBD.setText("Ruta de acceso a las bases de datos:");

        fieldRutaBD.setText(rutaBD);
        fieldRutaBD.setEnabled(false);

        btModificarRutaBD.setText("Modificar");

        lblUltimaInstitucion.setText("Última institucion utilizada:");

        lblDetalleUltimaInstitucion.setText(ultimaBD);

        lblRutaFotos.setText("Ruta de acceso a las fotos:");

        fieldRutaFotos.setText("P:\\Proyectos Personales pCloud\\FotosRo\\PruebasFotos");
        fieldRutaFotos.setEnabled(false);

        btModificarRutaFotos.setText("Modificar");

        lblNombreArchivos.setText("Nombres de archivos:");

        fieldPreNroFoto.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        fieldPreNroFoto.setText("_DSC");
        fieldPreNroFoto.setEnabled(false);

        lblNroFoto.setText("+ Nº de Foto +");

        fieldPostNroFoto.setText(".jpg");
        fieldPostNroFoto.setEnabled(false);

        btModificarNombreArchivos.setLabel("Modificar");

        lblRutaCopiaImprenta.setText("Ruta de copias para imprenta:");

        fieldRutaCopiaImprenta.setText("P:\\Proyectos Personales pCloud\\FotosRo\\PruebasFotos");
        fieldRutaCopiaImprenta.setToolTipText("");
        fieldRutaCopiaImprenta.setEnabled(false);

        btModificarRutaCopiaImprenta.setText("Modificar");

        panelAccionesRapidas.setBorder(javax.swing.BorderFactory.createTitledBorder("Acciones Rápidas"));

        btCrearCopiasImprenta.setText("Crear copias de las fotos para la imprenta");

        javax.swing.GroupLayout panelAccionesRapidasLayout = new javax.swing.GroupLayout(panelAccionesRapidas);
        panelAccionesRapidas.setLayout(panelAccionesRapidasLayout);
        panelAccionesRapidasLayout.setHorizontalGroup(
            panelAccionesRapidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAccionesRapidasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btCrearCopiasImprenta)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelAccionesRapidasLayout.setVerticalGroup(
            panelAccionesRapidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAccionesRapidasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btCrearCopiasImprenta)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout tabConfigLayout = new javax.swing.GroupLayout(tabConfig);
        tabConfig.setLayout(tabConfigLayout);
        tabConfigLayout.setHorizontalGroup(
            tabConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabConfigLayout.createSequentialGroup()
                .addGroup(tabConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabConfigLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(panelAccionesRapidas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(tabConfigLayout.createSequentialGroup()
                        .addContainerGap(48, Short.MAX_VALUE)
                        .addGroup(tabConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tabConfigLayout.createSequentialGroup()
                                .addGroup(tabConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblRutaBD)
                                    .addComponent(lblUltimaInstitucion)
                                    .addComponent(lblRutaFotos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(tabConfigLayout.createSequentialGroup()
                                .addGroup(tabConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNombreArchivos, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblRutaCopiaImprenta, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(38, 38, 38)))
                        .addGroup(tabConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tabConfigLayout.createSequentialGroup()
                                .addGroup(tabConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(tabConfigLayout.createSequentialGroup()
                                        .addComponent(fieldPreNroFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblNroFoto)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(fieldPostNroFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btModificarNombreArchivos))
                                    .addGroup(tabConfigLayout.createSequentialGroup()
                                        .addComponent(fieldRutaCopiaImprenta, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btModificarRutaCopiaImprenta)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(tabConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(tabConfigLayout.createSequentialGroup()
                                    .addComponent(fieldRutaFotos, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btModificarRutaFotos))
                                .addGroup(tabConfigLayout.createSequentialGroup()
                                    .addComponent(fieldRutaBD, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btModificarRutaBD))
                                .addComponent(lblDetalleUltimaInstitucion, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        tabConfigLayout.setVerticalGroup(
            tabConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabConfigLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(tabConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRutaBD)
                    .addComponent(fieldRutaBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btModificarRutaBD))
                .addGap(27, 27, 27)
                .addGroup(tabConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUltimaInstitucion)
                    .addComponent(lblDetalleUltimaInstitucion))
                .addGap(26, 26, 26)
                .addGroup(tabConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRutaFotos)
                    .addComponent(fieldRutaFotos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btModificarRutaFotos))
                .addGap(18, 18, 18)
                .addGroup(tabConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreArchivos)
                    .addComponent(fieldPreNroFoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNroFoto)
                    .addComponent(fieldPostNroFoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btModificarNombreArchivos))
                .addGap(18, 18, 18)
                .addGroup(tabConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRutaCopiaImprenta)
                    .addComponent(fieldRutaCopiaImprenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btModificarRutaCopiaImprenta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 321, Short.MAX_VALUE)
                .addComponent(panelAccionesRapidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        tabbedPane.addTab("Configuración", tabConfig);

        javax.swing.GroupLayout panelTabsLayout = new javax.swing.GroupLayout(panelTabs);
        panelTabs.setLayout(panelTabsLayout);
        panelTabsLayout.setHorizontalGroup(
            panelTabsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        panelTabsLayout.setVerticalGroup(
            panelTabsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTabsLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(tabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 746, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelTabs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelTabs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAgregarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAgregarCursoActionPerformed
        DialogCurso nc = new DialogCurso(this, "Nuevo Curso", true);
        modeloCursos.removeAllElements();
        cargarModelos();
    }//GEN-LAST:event_btAgregarCursoActionPerformed

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_F5) {
            // TO DO: refrescar frame
            System.out.println("Apretaste F5");
            /*dispose();
            FramePrincipal fp = new FramePrincipal();*/
        }
    }//GEN-LAST:event_formKeyReleased

    private void cboCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboCursoActionPerformed
        System.out.println(bd.obtenerAlumnos((Curso) cboCurso.getSelectedItem()));
    }//GEN-LAST:event_cboCursoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
 /*try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
         */
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FramePrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAgregarAlumno;
    private javax.swing.JButton btAgregarCurso;
    private javax.swing.JButton btAgregarInstitucion;
    private javax.swing.JButton btCrearCopiasImprenta;
    private javax.swing.JButton btMasCarnet;
    private javax.swing.JButton btMasCombo1;
    private javax.swing.JButton btMasCombo2;
    private javax.swing.JButton btMasGrupalM;
    private javax.swing.JButton btMasGrupalT;
    private javax.swing.JButton btMasIndividual;
    private javax.swing.JButton btMasSenioM;
    private javax.swing.JButton btMasSenioT;
    private javax.swing.JButton btMenosCarnet;
    private javax.swing.JButton btMenosGrupalM;
    private javax.swing.JButton btMenosGrupalT;
    private javax.swing.JButton btMenosIndividual;
    private javax.swing.JButton btMenosSenioM;
    private javax.swing.JButton btMenosSenioT;
    private javax.swing.JButton btModificarAlumno;
    private javax.swing.JButton btModificarNombreArchivos;
    private javax.swing.JButton btModificarRutaBD;
    private javax.swing.JButton btModificarRutaCopiaImprenta;
    private javax.swing.JButton btModificarRutaFotos;
    private javax.swing.JComboBox<String> cboAño;
    private javax.swing.JComboBox<Curso> cboCurso;
    private javax.swing.JComboBox<String> cboInstitucion;
    private javax.swing.JTextField fieldFechaSacadaCarnet;
    private javax.swing.JTextField fieldFechaSacadaGrupalM;
    private javax.swing.JTextField fieldFechaSacadaGrupalT;
    private javax.swing.JTextField fieldFechaSacadaIndividual;
    private javax.swing.JTextField fieldFechaSacadaSenioM;
    private javax.swing.JTextField fieldFechaSacadaSenioT;
    private javax.swing.JTextField fieldIdAlumno;
    private javax.swing.JTextField fieldMaestra;
    private javax.swing.JTextField fieldNombre;
    private javax.swing.JTextField fieldNroFotoCarnet;
    private javax.swing.JTextField fieldNroFotoGrupalM;
    private javax.swing.JTextField fieldNroFotoGrupalT;
    private javax.swing.JTextField fieldNroFotoIndividual;
    private javax.swing.JTextField fieldNroFotoSenioM;
    private javax.swing.JTextField fieldNroFotoSenioT;
    private javax.swing.JTextField fieldPago;
    private javax.swing.JTextField fieldPedidoCarnet;
    private javax.swing.JTextField fieldPedidoGrupalM;
    private javax.swing.JTextField fieldPedidoGrupalT;
    private javax.swing.JTextField fieldPedidoIndividual;
    private javax.swing.JTextField fieldPedidoSenioM;
    private javax.swing.JTextField fieldPedidoSenioT;
    private javax.swing.JTextField fieldPostNroFoto;
    private javax.swing.JTextField fieldPreNroFoto;
    private javax.swing.JTextField fieldRestante;
    private javax.swing.JTextField fieldRutaBD;
    private javax.swing.JTextField fieldRutaCopiaImprenta;
    private javax.swing.JTextField fieldRutaFotos;
    private javax.swing.JTextField fieldTotal;
    private javax.swing.JTextField fieldTurno;
    private javax.swing.JLabel lblAño;
    private javax.swing.JLabel lblCarnet;
    private javax.swing.JLabel lblCurso;
    private javax.swing.JLabel lblDetalleUltimaInstitucion;
    private javax.swing.JLabel lblFechaSacada;
    private javax.swing.JLabel lblFotoAlumno;
    private javax.swing.JLabel lblFotoNro;
    private javax.swing.JLabel lblGrupalM;
    private javax.swing.JLabel lblGrupalT;
    private javax.swing.JLabel lblIdAlumno;
    private javax.swing.JLabel lblIndividual;
    private javax.swing.JLabel lblInstitucion;
    private javax.swing.JLabel lblMaestra;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombreArchivos;
    private javax.swing.JLabel lblNroFoto;
    private javax.swing.JLabel lblPago;
    private javax.swing.JLabel lblPedidos;
    private javax.swing.JLabel lblRegistrosEncontrados;
    private javax.swing.JLabel lblRestante;
    private javax.swing.JLabel lblRutaBD;
    private javax.swing.JLabel lblRutaCopiaImprenta;
    private javax.swing.JLabel lblRutaFotos;
    private javax.swing.JLabel lblSenioM;
    private javax.swing.JLabel lblSenioT;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTurno;
    private javax.swing.JLabel lblUltimaInstitucion;
    private javax.swing.JPanel panelAccionesRapidas;
    private javax.swing.JScrollPane panelAlumnos;
    private javax.swing.JPanel panelDatosAlumno;
    private javax.swing.JPanel panelFotoAlumno;
    private javax.swing.JPanel panelFotos;
    private javax.swing.JPanel panelObservaciones;
    private javax.swing.JPanel panelPago;
    private javax.swing.JPanel panelTabs;
    private javax.swing.JScrollPane scrollObs;
    private javax.swing.JPanel tabAlumnos;
    private javax.swing.JPanel tabConfig;
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JTable tablaAlumnos;
    private javax.swing.JTextArea textObs;
    // End of variables declaration//GEN-END:variables

}
